kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    avp.kubernetes.io/path: "saastobs/kv-secrets/wavefront-k8s-config-repo"
stringData:
  url: git@github.com:sunnylabs/wavefront-kafka-k8s-config
  sshPrivateKey: |
    <kafka.truststore>
